### ISSUE TITLE
Issue running veganbagel

### ISSUE THREAD

**Issue by zzzdef** [BrainImAccs/veganbagel#1]
Thank you for the project.
I have issues making it work with the named requirement steps.
The running script results in "estimateVolumechanges failed" when processing the "cat12.mat" file.
Output:
Item registration: No field(s) named
Item expots: No field(s) named
Item output: No field(s) named

I am running the 2019b version of matlab, could that be the issue?

**Comment by crubb** [comment]
Hey,

a bit mysterious ;) Could you post the full debug log?

Best,
crubb

_**Please note:** We recommend thoroughly anonymizing any scan before generating debug logs. If the log may still contain sensitive information, consider mailing it to brainimaccs at med.uni-duesseldorf.de with a link to the issue/pull request._

**Comment by crubb** [comment]
Please try our latest Docker-based veganbagel version!
