### ISSUE TITLE
Error in CAT12.7 when building dockerfile

### ISSUE THREAD

**Issue by medmen** [BrainImAccs/veganbagel#4]
Maybe this is somewhat related to issue #3?
When trying to build from downloaded dockerfile i get the following error:

```
+ unzip -q /opt/CAT12.7_r1743_R2017b_MCR_Linux.zip -d /opt
+ mv /opt/CAT12.7_r1743_R2017b_MCR_Linux /opt/cat12
+ rm -f /opt/CAT12.7_r1743_R2017b_MCR_Linux.zip
+ LD_LIBRARY_PATH=/opt/mcr-R2017b/v93/runtime/glnxa64:/opt/mcr-R2017b/v93/bin/glnxa64:/opt/mcr-R2017b/v93/sys/os/glnxa64:/opt/mcr-R2017b/v93/sys/opengl/lib/glnxa64:/opt/mcr-R2017b/v93/extern/bin/glnxa64 /opt/cat12/spm12 function exit
Error in extracting CTF file to '/opt/cat12/spm12_mcr'. Details: 'Could not create file: /opt/cat12/spm12_mcr/spm12/file:%2Fusr%2Flocal%2FMATLAB%2FR2017a%2Ftoolbox%2Fmatlab%2Fdepfun%2F%2Bmatlab%2F%2Bdepfun%2F%2Binternal%2Frequirements%5Fglnxa64%5Fdfdb?mode=ro&vfs=unix-none'
```
Im a newby with docker, so i dont have a clue how to fix this..

**Comment by crubb** [comment]
Hey,

that error is past the stage of #3. Have not seen it before, but I somewhat suspect, that the disk or Docker disk image is full (are you by any chance using a Mac? Maybe see  https://docs.docker.com/desktop/mac/space/).

Best,
crubb

**Comment by medmen** [comment]
No mac here, running Ubuntu 20.04
there is plenty of disc space left (>100 G) 

Oh, just found my problem.. I was playing with podman a while ago and had an alias "docker" pointing to podman. This obvoiusly didn't work, but i am surprised podman got that far... ;-) 

Closing this as solved, thanx for your help!!
